name: ci

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-18.04
    container: hadolint/hadolint:latest
    steps:
    - uses: actions/checkout@v2
    - name: Run hadolint
      run: hadolint Dockerfile

  test:
    needs: [lint]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Run builder script with arguments `--help`
      run: ./build-kernel.sh --help

  release:
    needs: [test]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set variables
      id: vars
      run: |
        echo ::set-output \
          name=repository::tschaffter/${{ github.event.repository.name }}
        echo ::set-output name=user::tschaffter
        if [[ ${GITHUB_REF} = refs/tags/* ]]
        then
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}
          echo ::set-output name=push::true
        else
          echo ::set-output name=version::test
          echo ::set-output name=push::false
        fi

    - name: Build Dockerfile.base
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ steps.vars.outputs.repository }}
        tags: latest, ${{ steps.vars.outputs.version }}
        push: ${{ steps.vars.outputs.push }}